#!/usr/bin/env bash
# This script installs and configures Nginx on an Ubuntu server

# Install Nginx
apt-get update
apt-get -y install nginx

# Configure Nginx to listen on port 80
sed -i 's/^\(listen\s*\).*$/\1 80;/g' /etc/nginx/sites-available/default

# Restart Nginx without using systemctl
/etc/init.d/nginx restart

# Create HTML file with "Hello World!" message
echo "Hello World!" > /var/www/html/index.html

