#!/usr/bin/env bash
# This script installs nginx web server and configures it to serve a page with the string "Hello World!"

# Install nginx
apt-get -y update
apt-get -y install nginx

# Create a default HTML file with "Hello World!"
echo "Hello World!" > /usr/share/nginx/html/index.html

# Replace default nginx configuration to make it listen on port 80
sed -i 's/80 default_server;/80 default_server;\n\t\tlisten [::]:80 default_server;/g' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart

