#!/usr/bin/env bash
# This script configures an Nginx server to redirect /redirect_me to another page with a 301 Moved Permanently response

# Install Nginx if not already installed
if ! command -v nginx &>/dev/null; then
    apt-get update
    apt-get install -y nginx
fi

# Configure the redirection
REDIRECT_CONFIG="/etc/nginx/sites-available/redirect_me"
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}" >"$REDIRECT_CONFIG"

# Create a symbolic link to enable the site
ln -sf "$REDIRECT_CONFIG" /etc/nginx/sites-enabled/

# Test Nginx configuration and restart the server
nginx -t && nginx -s reload

