#!/usr/bin/env bash
# This script configures Nginx to have a custom 404 page

# Install Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Create a custom 404 HTML page
echo "<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>Ceci n'est pas une page</h1>
</body>
</html>" | sudo tee /var/www/html/custom_404.html

# Configure Nginx to use the custom 404 page
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /var/www/html;
        internal;
    }
}
EOF'

# Restart Nginx to apply changes
sudo service nginx restart

