#!/usr/bin/env bash

# This Bash script configures a new Ubuntu machine to have a custom 404 page for Nginx.

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

# Configure Nginx to use custom 404 page
sudo sed -i '/error_page 404/c\        error_page 404 /404.html;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl restart nginx

