#!/usr/bin/env bash
# This script configures Nginx to add a custom HTTP response header

# Install Nginx if not already installed
if ! command -v nginx &> /dev/null; then
    apt-get update
    apt-get install -y nginx
fi

# Configure Nginx to add custom header
echo 'add_header X-Served-By $hostname;' | sudo tee -a /etc/nginx/sites-available/default >/dev/null

# Restart Nginx to apply changes
service nginx restart

