#!/usr/bin/env bash

# This Bash script displays listening ports

# Display listening TCP ports
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
netstat -tuln | grep '^tcp' | awk '{print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6"\t"$7}' | sed 's/:::/[::]/g'

# Display listening UDP ports
netstat -uln | grep '^udp' | awk '{print $1"\t"$2"\t"$3"\t"$4"\t\t\t"$6"\t"$7}' | sed 's/:::/[::]/g'

