#!/usr/bin/env bash
# This script checks if nginx is running, if not, it starts it
service nginx status | grep -q "not running"
service nginx start > /dev/null
curl -s 0:80 | grep -q "Welcome to nginx"

