#!/usr/bin/env bash
# This script manages the manage_my_process daemon.

case "$1" in
    start|stop|restart)
        sudo ./manage_my_process "$1"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

