#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays the data.

awk '{print $1 " " $4 " " $9}' | awk '{count[$2 " " $3]++} END {for (ip_status in count) print count[ip_status], ip_status}' | sort -rn

