#!/usr/bin/env bash
# This script changes the IP address resolution for localhost and facebook.com

# Update hosts file for localhost
sudo sed -i 's/^127.0.0.1\s*localhost$/127.0.0.2 localhost/g' /etc/hosts

# Update hosts file for facebook.com
sudo sed -i 's/^.*\bfacebook\.com\b.*$/8.8.8.8 facebook.com/g' /etc/hosts

# Flush DNS cache
sudo systemd-resolve --flush-caches

