#!/usr/bin/env bash
# This script configures an Ubuntu server as follows:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

# Backup the current hosts file
sudo cp /etc/hosts ~/hosts.new

# Update the new hosts file with the desired configurations
echo "127.0.0.2 localhost" >> ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new

# Replace the original hosts file with the new one
sudo cp -f ~/hosts.new /etc/hosts

# Clean up temporary files
rm ~/hosts.new

