#!/usr/bin/env bash
# This script changes the IP address resolution for localhost and facebook.com

# Update hosts file
sudo sed -i 's/^127.0.0.1.*localhost$/127.0.0.2 localhost/g' /etc/hosts
sudo sed -i 's/^.*facebook.com$/8.8.8.8 facebook.com/g' /etc/hosts

# Flush DNS cache
sudo systemd-resolve --flush-caches

