#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine it's executed on

ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'

