#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on all active IPs on port 8080

# Update Nginx configuration to run as nginx user
sed -i 's/user\s*nginx;/user nginx nginx;/g' /etc/nginx/nginx.conf

# Restart Nginx
service nginx restart

